### Spring 공통 문서 관리
common:
  api-doc:
    title: "License Agent API"
    description: "라이센스 에이전트 API"
    version: "1.0"
    email: "demo@exmple.com"

### Spring 문서 관리
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api
    enabled: true
  # 일반화된 응답 사용 여부 결정(Handler 충돌방지)
  override-with-generic-response: false