plugins {
    id 'java'
    // https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

ext {
    libName = 'validator'
    libVersion = version
}


jar {
    enabled = true
    archiveBaseName.set(libName)
    archiveVersion.set(libVersion)

    dependsOn shadowJar
}

shadowJar {
    archiveBaseName.set(libName)
    archiveVersion.set(libVersion)
    archiveClassifier.set('')
    mergeServiceFiles()
}

bootJar {
    enabled = false
}

dependencies {
    implementation fileTree(dir: '../lib', includes: [
            "jwt4j.lite-*.jar",
            "jwt4j.lite-*-*.jar"
    ])
    implementation project(':license-common')
}
