plugins {
    id 'java'
}

bootJar {
    enabled = true
    archiveClassifier = ''
}

jar {
    enabled = true
    exclude('**/*Properties.class')
    exclude('**/*Application.class')
    exclude('**/controller/**')
}

dependencies {
    implementation fileTree(dir: '../lib', includes: [
            "jwt4j.lite-*.jar",
            "jwt4j.lite-*-*.jar"
    ])
    implementation project(':license-common')
}
