plugins {
    id 'java'
    id 'war'
}

war {
    enabled = false
}

dependencies {
    runtimeOnly 'com.h2database:h2'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation fileTree(dir: '../lib', includes: [
            "JsonWebToken-*.jar"
    ])
    implementation project(':license-common')
}
