plugins {
    id 'java'
    id 'war'
}

war {
    enabled = false
}

dependencies {
    runtimeOnly 'com.h2database:h2'
    implementation fileTree(dir: '../lib', includes: [
            "JsonWebToken-*.jar"
    ])
    implementation project(':license-common')
    implementation group: 'org.json', name: 'json', version: '20230227'
}
